[package]
name = "kernel-pet"
version = "0.5.0"
description = "Kernel desktop companion"
authors = ["Gabriel Grondin"]
repository = "https://github.com/GGLinnk/pets"
edition = "2024"
rust-version = "1.90"

[lib]
name = "kernel_pet_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.7.0" }

[dependencies]
tauri = { version = "2.12.0", features = ["tray-icon", "macos-private-api"] }
